development:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://localhost:<%= ENV['FCREPO_DEVELOPMENT_PORT'] || 8984 %>/rest
  base_path: /dev
test:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://localhost:<%= ENV['FCREPO_TEST_PORT'] || 8986 %>/rest
  base_path: /test
production:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://localhost:8983/fcrepo-webapp-4.7.1/rest
  base_path: /prod
