development:
  adapter: redis
  url: redis://<%= ENV.fetch('REDIS_DEVELOPMENT_HOST', 'localhost') %>:<%= ENV.fetch('REDIS_DEVELOPMENT_PORT', 6379) %>

test:
  adapter: async

production:
  adapter: redis
  url: redis://<%= ENV.fetch('REDIS_PRODUCTION_HOST', 'localhost') %>:<%= ENV.fetch('REDIS_PRODUCTION_PORT', 6379) %>/1
  channel_prefix: data2paper_production
