# This is a sample config file that points to a solr server for each environment
development:
  url: <%= ENV['SOLR_DEVELOPMENT_URL'] || 'http://localhost:8983/solr/data2paper-development' %>
test:
  url: <%= ENV['SOLR_TEST_URL'] || 'http://localhost:8983/solr/data2paper-test' %>
production:
  url: <%= ENV['SOLR_PRODUCTION_URL'] || 'http://localhost:8983/solr/data2paper-production' %>
