terms:
    - id: http://creativecommons.org/licenses/by/3.0/
      term: Attribution 3.0 Unported (CC BY 3.0)
      active: true
    - id: http://creativecommons.org/licenses/by-sa/3.0/
      term: Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)
      active: true
    - id: http://creativecommons.org/licenses/by-nc/3.0/
      term: Attribution-NonCommercial 3.0 Unported (CC BY-NC 3.0)
      active: true
    - id: http://creativecommons.org/licenses/by-nd/3.0/
      term: Attribution-NoDerivs 3.0 Unported (CC BY-ND 3.0)
      active: true
    - id: http://creativecommons.org/licenses/by-nc-nd/3.0/
      term: Attribution-NonCommercial-NoDerivs 3.0 Unported (CC BY-NC-ND 3.0)
      active: true
    - id: http://creativecommons.org/licenses/by-nc-sa/3.0/
      term: Attribution-NonCommercial-ShareAlike 3.0 Unported (CC BY-NC-SA 3.0)
      active: true
    - id: http://creativecommons.org/publicdomain/mark/1.0/
      term: Public Domain Mark 1.0
      active: true
    - id: http://creativecommons.org/publicdomain/zero/1.0/
      term: CC0 1.0 Universal
      active: true
    - id: http://www.europeana.eu/portal/rights/rr-r.html
      term: All rights reserved
      active: true
    - id: UNKNOWN
      term: UNKNOWN
      active: true
